from cavalo import Cavalo

cavalo1 = Cavalo("Larry", "Azul", 10)
cavalo2 = Cavalo("Darry", "Amarelo", 11)
cavalo3 = Cavalo("Perry", "Verde", 12)

cavalo1.mover()
cavalo2.mover()
cavalo3.mover()
cavalo1.mover()
cavalo2.mover()
cavalo3.mover()
cavalo1.mover()
cavalo2.mover()
cavalo3.mover()
cavalo1.mover()
cavalo2.mover()
cavalo3.mover()
cavalo1.mover()
cavalo2.mover()
cavalo3.mover()
cavalo1.mover()
cavalo2.mover()
cavalo3.mover()
